### ISSUE TITLE
Certificate error on windows

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena-plugin-aws#33]
```
C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (Seahorse::Client::NetworkingError)
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:858:in `start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/seahorse/client/net_http/connection_pool.rb:285:in `start_session'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/seahorse/client/net_http/connection_pool.rb:92:in `session_for'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/seahorse/client/net_http/handler.rb:119:in `session'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/seahorse/client/net_http/handler.rb:71:in `transmit'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/seahorse/client/net_http/handler.rb:45:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/seahorse/client/plugins/content_length.rb:12:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/xml/error_handler.rb:8:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/request_signer.rb:88:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/retry_errors.rb:88:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/retry_errors.rb:119:in `retry_request'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/retry_errors.rb:102:in `retry_if_possible'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/retry_errors.rb:90:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/retry_errors.rb:119:in `retry_request'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/retry_errors.rb:102:in `retry_if_possible'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/retry_errors.rb:90:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/retry_errors.rb:119:in `retry_request'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/retry_errors.rb:102:in `retry_if_possible'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/retry_errors.rb:90:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/query/handler.rb:27:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/seahorse/client/plugins/response_target.rb:21:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/seahorse/client/request.rb:70:in `send_request'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-core-2.9.7/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-resources-2.9.7/lib/aws-sdk-resources/request.rb:24:in `call'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-resources-2.9.7/lib/aws-sdk-resources/operations.rb:139:in `all_batches'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-resources-2.9.7/lib/aws-sdk-resources/operations.rb:151:in `limited_batches'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-resources-2.9.7/lib/aws-sdk-resources/collection.rb:18:in `each'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-resources-2.9.7/lib/aws-sdk-resources/collection.rb:18:in `each'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-resources-2.9.7/lib/aws-sdk-resources/collection.rb:57:in `to_a'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/aws-sdk-resources-2.9.7/lib/aws-sdk-resources/collection.rb:57:in `first'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/kontena-plugin-aws-0.2.6/lib/kontena/machine/aws/common.rb:47:in `block in resolve_security_groups_to_ids'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/kontena-plugin-aws-0.2.6/lib/kontena/machine/aws/common.rb:41:in `map'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/kontena-plugin-aws-0.2.6/lib/kontena/machine/aws/common.rb:41:in `resolve_security_groups_to_ids'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/kontena-plugin-aws-0.2.6/lib/kontena/machine/aws/master_provisioner.rb:57:in `run!'
        from C:/Users/Kaitsu/.kontena/gems/2.3.3/gems/kontena-plugin-aws-0.2.6/lib/kontena/plugin/aws/master/create_command.rb:41:in `execute'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.6/lib/kontena/command.rb:191:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.6/lib/kontena/command.rb:191:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.6/lib/kontena/command.rb:191:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.6/lib/kontena/command.rb:191:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/kontena-cli-1.1.6/bin/kontena:16:in `<top (required)>'
        from C:/Ruby23-x64/bin/kontena:22:in `load'
        from C:/Ruby23-x64/bin/kontena:22:in `<main>'
```

See: https://github.com/aws/aws-sdk-core-ruby/issues/166

**Comment by kvirkki** [comment]
This error happens when trying to use the Kontena AWS plugin. I suspect it has something to do with Ruby not having SSL cert bundle of trusted certificates available on Windows.

**Comment by kvirkki** [comment]
Finally, got things working. To solve this issue, you need to get a PEM-formatted file that contains all the CA certificates you want to trust. Then you need to set SSL_CERT_FILE environment variable to point to this file and things should work! :) Just be careful to download the file from a location you trust! See more here: http://stackoverflow.com/questions/5720484/how-to-solve-certificate-verify-failed-on-windows#answer-16134586
